name: build-gh-pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Artifacts
        uses: actions/upload-pages-artifact@v2
      - name: Deploy
        uses: actions/deploy-pages@v2